version: 2.1

orbs:
  golang-ci: epavlova/golang-ci@0.2.2

workflows:
  version: 2.1
  tests_and_docker:
    jobs:
      - golang-ci/build-and-test:
          name: build-and-test-project

      - golang-ci/scan:
          name: scan-dependencies
          context: publish-orbs
          requires:
            - build-and-test-project

      - golang-ci/docker-build:
          name: build-docker-image
          requires:
            - build-and-test-project
