version: 2.1

orbs:
  golang-ci: epavlova/golang-ci@0.1.0

workflows:
  version: 2.1
  tests_and_docker:
    jobs:
      - golang-ci/build-and-test:
          name: build-and-test-project
      - golang-ci/docker-build:
          name: build-docker-image
          requires:
            - build-and-test-project
